wsgi/openshift/apps/registros/urls.py
# -*- coding: UTF8 -*-
from django.conf.urls import *

urlpatterns = patterns('registros.views',
    url(r'^$', 'registrar', name='registrar'),
    url(r'^(?P<ponto>\d+)/ponto/$', 'registrar_ponto',
    	name='registrar_ponto'),
)

wsgi/openshift/urls.py
# -*- coding: UTF8 -*-
from django.conf.urls import *
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.conf import settings
from django.contrib import admin
admin.autodiscover()


# includes
urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
)
# Core Tweet
urlpatterns += patterns('apps.core.views',
    url(r'^$', 'pesquisar', name='pesquisar'),
    # Ponto Vitória fora do ar
    url(r'^(\w+)/$',
        RedirectView.as_view(
            url=('http://vitoria.es.gov.br/noticia/'
                'ponto-vitoria-passa-por-atualizacao-e-modernizacao-15798'),
            permanent=False),
        name='out-of-service'),

    url(r'^pesquisar', 'pesquisar', name='pesquisar'),
    url(r'^pontos/$', 'pontos', name='pontos'),
    url(r'^pontos/local/$', 'pontos_local', name='pontos_local'),
    url(r'^ponto/(?P<ponto>\d+)/linhas/$', 'linhas', name='linhas'),
    url(r'^ponto/(?P<ponto>\d+)/linha/(?P<linha>\d+)/horarios/$',
        'previsoes', name='previsoes'),
)
# Registros
urlpatterns += patterns('apps.registros.views',
    url(r'^registro/', include('registros.urls', namespace='registro')),
)
# Media
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

wsgi/openshift/apps/registros/models.py
# -*- coding: UTF8 -*-

from django.db import models
from registros.model_choices import HORAS, MINUTOS, LEMBRAR


class Registros(models.Model):
    """
    Você será mencionado em um tweet (@twitnerario)
    com o horário aproximado do seu ônibus.
    """
    criado_em = models.DateTimeField('criado em', auto_now_add=True)
    twitter = models.CharField('twitter', max_length=15)
    ponto = models.CharField(u'ponto', max_length=4)
    linha = models.CharField(u'linha', max_length=6)
    horas = models.PositiveSmallIntegerField(u'quero ser lembrado às',
        choices=HORAS, default=7)
    minutos = models.PositiveSmallIntegerField(u':', choices=MINUTOS,
        default=0)
    lembrar = models.PositiveSmallIntegerField(u'me lembre',
        choices=LEMBRAR, default=0)
    fim_de_semana = models.BooleanField(u'incluir fim de semana?',
        default=False)
    falhou = models.BooleanField(u'falhou?', default=False)

    class Meta:
        verbose_name = u"Registro"

    def __unicode__(self):
        return '@{0} {1} {2}:{3}'.format(self.twitter, self.linha,
            self.horas, self.minutos)

wsgi/openshift/apps/registros/forms.py
# -*- coding: UTF8 -*-

from django import forms
from django.forms import ModelForm
from form_utils.forms import BetterModelForm
from registros.models import Registros


class RegistrosForm(BetterModelForm):
    """Formulário de registros de tweets"""

    class Meta:
        model = Registros
        
        fieldsets = [
            ('Registro', {
                'fields': ('twitter', 'ponto', 'linha', 'horas',
                            'minutos', 'lembrar', 'fim_de_semana'),
                'classes': ['registro']
                })
        ]

    def __init__(self, *args, **kwargs):
        super(RegistrosForm, self).__init__(*args, **kwargs)

        self.fields['linha'].widget = forms.Select()
        self.fields['fim_de_semana'].widget.attrs = {
            'style': 'display:none'}

    def clean(self):
        twitter = self.cleaned_data.get('twitter')
        linha = self.cleaned_data.get('linha')
        ponto = self.cleaned_data.get('ponto')
        horas = self.cleaned_data.get('horas')
        minutos = self.cleaned_data.get('minutos')
        # Verifica se registro já existe
        if Registros.objects.filter(twitter=twitter, ponto=ponto, linha=linha,
            horas=horas, minutos=minutos).exists():
            raise forms.ValidationError(
                u'Este registro já existe para o twitter {}'.format(twitter))
            
        return self.cleaned_data

wsgi/openshift/apps/registros/views.py
# -*- coding: UTF8 -*-

from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.template import Context, RequestContext
from registros.models import Registros
from registros.forms import RegistrosForm
from django.http import HttpResponse, HttpResponseRedirect


def registrar(request):
    """
    Recebe formulário e registra tweet
    """

    form = RegistrosForm(request.POST or None)
    if form.is_valid():
        form.save()
        context = {
            'twitter': request.POST['twitter'],
            'h': request.POST['horas'],
            'm': request.POST['minutos']
        }
        return render_to_response('registros/sucesso.html',
            context_instance=RequestContext(request,context))

    return render_to_response('registros/registro.html',
        context_instance=RequestContext(request, {'form': form}))


def registrar_ponto(request, ponto):
    """
    Recebe número do ponto e preenche o formulário
    """

    form = RegistrosForm(initial={'ponto': ponto})
    if request.method == 'POST':
        form = RegistrosForm(request.POST)
        if form.is_valid():
            form.save()
            context = {
                'twitter': request.POST['twitter'],
                'h': request.POST['horas'],
                'm': request.POST['minutos']
            }
            return render_to_response('registros/sucesso.html',
                context_instance=RequestContext(request,context))

    return render_to_response('registros/registro.html',
        context_instance=RequestContext(request, {'form': form}))

wsgi/openshift/templates/registros/horarios-linha.html
{% extends "base.html" %}
{% load core_tags %}
{% block title %}Horarios{% endblock %}
{% block menu %}
<!-- <li><a href="/">Home</a></li>
<li><a href="/knowledge-base/">Knowledge Base</a></li>
<li><a href="/articles/">Articles</a></li>
<li class="active"><a href="/faq/">Faq</a></li>
<li><a href="/features/">Features</a></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages</a>
  <ul class="dropdown-menu">
    <li><a href="/contact/">Contact</a></li>
    <li><a href="/full/">Full</a></li>
  </ul>
</li> -->
{% endblock %}
{% block page_header %}
<!-- PAGE HEADER -->
<div id="page-header-container">
  <div class="container">
    <div class="page-header row">
      <div class="span8">
        <h1>Linha nº {{ linha }} ponto nº {{ ponto }}</h1>
        {% if horarios %}<p class="tagline">Lista de horários</p>{% endif %}
      </div>
      <div class="span4">
        <form role="search" method="get" id="searchform" class="form-search" action="/pesquisar/">
          <label class="hide" for="s" >Pesquisar por:</label>
          <input type="text" value="" name="s" class="searchajax search-query span4" placeholder="Rua, bairro ou ponto de referência.">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- PAGE CONTENT -->
<div id="wrap" class="container" role="document">
  <div id="content" class="row">
    <div class="span12">
      {% if horarios %}
      <div class="page-main">
      <!-- resultados-->
      {% for horario in horarios %}
        {{ horario }} minuto{% if horario > 1 %}s{% endif %}
        <hr class="separador">
      {% endfor %}
      </div>
      {% else %}
      <article class="type-faq hentry">
        <h3 class="entry-title">Nenhuma horario encontrado.</h3>
        <div class="entry-content" style="height: 240px;"></div>
      </article>
      {% endif %}
    </div>
  </div><!-- /#content -->
</div><!-- /#wrap -->
{% endblock %}
{% block footer_widgets %}{% endblock %}
{% block social_icons %}
<ul>
  <li class="social-icon twitter">
    <a class="fade-img" href="//twitter.com/twitnerario/" target="_blank" rel="tooltip" title="Twitter">
      <img src="{{ MEDIA_URL }}assets/img/social/icons_twitter.png" alt="Twitter" />
    </a>
  </li>
  <li class="social-icon facebook">
    <a class="fade-img" href="//www.facebook.com/twitnerario/" target="_blank" rel="tooltip" title="Facebook">
      <img src="{{ MEDIA_URL }}assets/img/social/icons_facebook.png" alt="Facebook" />
    </a>
  </li>
</ul>
{% endblock %}
{% block powered_by %}OpenSource project Nov 2011. Powered by <a target="_blank" href='//www.djangoproject.com/'>Django</a>{% endblock %}
{% block extra_js %}{% endblock %}

wsgi/openshift/templates/registros/linhas-ponto.html
{% extends "base.html" %}
{% load core_tags %}
{% block title %}Linhas{% endblock %}
{% block menu %}
<!-- <li><a href="/">Home</a></li>
<li><a href="/knowledge-base/">Knowledge Base</a></li>
<li><a href="/articles/">Articles</a></li>
<li class="active"><a href="/faq/">Faq</a></li>
<li><a href="/features/">Features</a></li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages</a>
  <ul class="dropdown-menu">
    <li><a href="/contact/">Contact</a></li>
    <li><a href="/full/">Full</a></li>
  </ul>
</li> -->
{% endblock %}
{% block page_header %}
<!-- PAGE HEADER -->
<div id="page-header-container">
  <div class="container">
    <div class="page-header row">
      <div class="span8">
        <h1>Ponto nº {{ ponto }}</h1>
        {% if linhas.data %}<p class="tagline">Lista de linhas</p>{% endif %}
      </div>
      <div class="span4">
        <form role="search" method="get" id="searchform" class="form-search" action="/pesquisar/">
          <label class="hide" for="s" >Pesquisar por:</label>
          <input type="text" value="" name="s" class="searchajax search-query span4" placeholder="Rua, bairro ou ponto de referência.">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block content %}
<!-- PAGE CONTENT -->
<div id="wrap" class="container" role="document">
  <div id="content" class="row">
    <div class="span12">
      {% if linhas.data %}
      <div class="page-main">
      <!-- resultados-->
      {% for linha in linhas.data %}
        <a href="/ponto/{{ ponto }}/linha/{{ linha.linha|split|first }}/horarios/">
          {{ linha.linha }}
          <hr class="separador">
        </a>
      {% endfor %}
      </div>
      {% else %}
      <article class="type-faq hentry">
        <h3 class="entry-title">Nenhuma linha encontrada.</h3>
        <div class="entry-content" style="height: 240px;"></div>
      </article>
      {% endif %}
    </div>
  </div><!-- /#content -->
</div><!-- /#wrap -->
{% endblock %}
{% block footer_widgets %}{% endblock %}
{% block social_icons %}
<ul>
  <li class="social-icon twitter">
    <a class="fade-img" href="//twitter.com/twitnerario/" target="_blank" rel="tooltip" title="Twitter">
      <img src="{{ MEDIA_URL }}assets/img/social/icons_twitter.png" alt="Twitter" />
    </a>
  </li>
  <li class="social-icon facebook">
    <a class="fade-img" href="//www.facebook.com/twitnerario/" target="_blank" rel="tooltip" title="Facebook">
      <img src="{{ MEDIA_URL }}assets/img/social/icons_facebook.png" alt="Facebook" />
    </a>
  </li>
</ul>
{% endblock %}
{% block powered_by %}OpenSource project Nov 2011. Powered by <a target="_blank" href='//www.djangoproject.com/'>Django</a>{% endblock %}
{% block extra_js %}{% endblock %}

wsgi/openshift/templates/registros/pontos-pesquisar.html
{% extends "base.html" %}
{% block title %}Pesquisar ponto{% endblock %}
{% block extra_head %}
  <link href="{{ MEDIA_URL }}css/pontos-pesquisar-ajustes.css" rel="stylesheet">
  <link href="{{ MEDIA_URL }}css/pontos-pesquisar.css" rel="stylesheet">{% endblock extra_head %}
{% block page_header %}{% endblock %}
{% block menu %}{% endblock %}
{% block content %}
<!-- HERO -->
<div id="hero">
  <div class="container">
    <!-- Hero title -->
    <div class="hero-title">
      <h1>Pesquisar pontos</h1>
    </div>
    <!-- Hero search -->
    <div class="hero-search">
      <form role="search" method="get" id="searchform" class="form-search" action="">
        <label class="hide" for="s">Pesquisar por:</label>
        <input type="text" name="s" class="searchajax search-query" placeholder="Rua, bairro ou ponto de referência." maxlength="25">
        <input type="submit" id="searchsubmit" value="Pesquisar" class="btn-black">
      </form>
      <p>
      <h4>Notícias - prefeitura de Vitória :( </h4>
      <a style="color: #666;" target="_blank" href="http://vitoria.es.gov.br/noticia/ponto-vitoria-passa-por-atualizacao-e-modernizacao-15798">Ponto Vitória (fora do ar) passa por atualização e modernização</a><br>
      <h6>Publicada em 26/09/2014, às 08h00 | Atualizada em 26/09/2014, às 10h07</h6><br>
      </p>
    </div>
    <!-- Hero boxes -->
    <div class="row boxes">
      {% if pontos.data %}
      <div class="span9">
        <div class="page-main">
        <!-- resultados-->
        {% for ponto in pontos.data %}
          <a href="/ponto/{{ ponto.ponto }}/linhas/">
            <div class="resultado">
              <span class="ponto">{{ ponto.ponto }}</span>
              <span class="endereco">
                <div class="lograd">{{ ponto.logradouro }} - {{ ponto.bairro }}</div>
                <div class="p_refer">{{ ponto.referencia }}</div>
              </span>
            </div>
            <hr class="separador">
          </a>
        {% endfor %}
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}
{% block footer_widgets %}{% endblock %}
{% block social_icons %}
<ul>
  <li class="social-icon twitter">
    <a class="fade-img" href="//twitter.com/twitnerario/" target="_blank" rel="tooltip" title="Twitter">
      <img src="{{ MEDIA_URL }}assets/img/social/icons_twitter.png" alt="Twitter" />
    </a>
  </li>
  <li class="social-icon facebook">
    <a class="fade-img" href="//www.facebook.com/twitnerario/" target="_blank" rel="tooltip" title="Facebook">
      <img src="{{ MEDIA_URL }}assets/img/social/icons_facebook.png" alt="Facebook" />
    </a>
  </li>
</ul>
{% endblock %}
{% block powered_by %}OpenSource project Nov 2011. Powered by <a target="_blank" href='//www.djangoproject.com/'>Django</a>{% endblock %}
{% block extra_js %}{% endblock %}

wsgi/openshift/templates/registros/registro.html
{% extends "base.html" %}
{% block content %}
  <style>
    .ui-combobox {
        position: relative;
        display: inline-block;
    }
    .ui-combobox-toggle {
        position: absolute;
        top: 0;
        bottom: 0;
        margin-left: -1px;
        padding: 0;
        /* adjust styles for IE 6/7 */
        *height: 1.7em;
        *top: 0.1em;
    }
    .ui-combobox-input {
        margin: 0;
        padding: 0.3em;
    }
  </style>
  <link rel="stylesheet" href="{{ MEDIA_URL }}css/overcast/jquery-ui-1.8.18.custom.css" type="text/css" charset="utf-8">
  <script type="text/javascript" src="{{MEDIA_URL}}js/prototype.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}js/pontos-array.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}js/titlecase.js"></script>
  <script type="text/javascript" src="{{MEDIA_URL}}js/twitnerario.registro.js"></script>
  <script type="text/javascript">
  jQuery(function() {
    jQuery("select#combobox_localizar").combobox();
    jQuery("select#combobox_localizar").bind( "autocompleteopen", function(event, ui) {
      alert('click');
    });
  });
  </script>
  <div class="row">
      <div class="span16">
      <form action="" method="post" style="margin-bottom: 10px;">{% csrf_token %}
        <fieldset style="margin-bottom: 10px;">
          <legend>Agendar tweet</legend>
          <div class="clearfix">
            {{ form.twitter.label_tag }}
            <div class="input">
                <div class="input-prepend">
                  <span class="add-on">@</span>
                {{ form.twitter }}
                </div>
            </div>
          </div>
          <!-- Localizar -->
          <!-- <div class="clearfix">
            <label for="id_localizar">Localizar</label>
            <div class="input">
              <div class="ui-widget">
                <select id="combobox_localizar">
                  <option value="">Select one...</option>
                  <option value="momo">ActionScript</option>
                  <option value="AppleScript">AppleScript</option>
                  <option value="Asp">Asp</option>
                  <option value="BASIC">BASIC</option>
                  <option value="C">C</option>
                </select>
                </div>
            </div>
          </div> -->
          <div class="clearfix">
            {{ form.ponto.label_tag }}
            <div class="input">
              <div class="input-prepend">
                <span class="add-on">Nº</span>
                  {{ form.ponto }}
                </div>
            </div>
          </div>
          <div class="clearfix">
            {{ form.linha.label_tag }}
            <div class="input">
                {{ form.linha }}
            </div>
          </div>
          <div class="hour clearfix">
            {{ form.horas.label_tag }}
            <div class="input">
                {{ form.horas }} : {{ form.minutos }}
            </div>
          </div>
          <div class="hour clearfix">
            {{ form.lembrar.label_tag }}
            <div class="input">
              {{ form.lembrar }}
            </div>
          </div>
          <div class="hour clearfix">
            {#{ form.fim_de_semana.label_tag }#}
            <div class="input">
                {{ form.fim_de_semana }}
            </div>
          </div>
          <div class="actions">
            <input class="btn primary" type="submit" value="Salvar Ponto">
            <a class="btn" href="/twitnerario/">Cancelar</a>
          </div>
              </fieldset>
          </form>
      </div>
  </div>
  <div class="row">
      <div id="content" class="span16"></div>
  </div>
{% endblock %}
{% block footer_inc %}
<script type="text/javascript" src="{{MEDIA_URL}}js/encontra-linhas.js"></script>
{% endblock %}

wsgi/openshift/templates/registros/registro_source.html
<h3>Registro</h3>
<!-- Formulario -->
<form action="#" method="post" class="form"><div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='06ee6b2090216562641bef85da01cf29' /></div>
  





<fieldset class="fieldset_Registro first">

<legend>Registro</legend>

<ul>



<li class="required">
  
  <label for="id_twitter">
  Twitter
  
  </label>
  <input id="id_twitter" type="text" name="twitter" value="@morenocunha" maxlength="15" />
</li>



<li class="required">
  
  <label for="id_ponto">
  Ponto número
  
  </label>
  <input type="text" name="ponto" value="5024" id="id_ponto" />
</li>



<li class="required">
  
  <label for="id_linha">
  Linha
  
  </label>
  <input type="text" name="linha" value="202" id="id_linha" />
</li>



<li class="required">
  
  <label for="id_horas">
  Estou no ponto às
  
  </label>
  <select name="horas" id="id_horas">
<option value="0">00</option>
<option value="1">01</option>
<option value="2">02</option>
<option value="3">03</option>
<option value="4">04</option>
<option value="5">05</option>
<option value="6">06</option>
<option value="7" selected="selected">07</option>
<option value="8">08</option>
<option value="9">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
</select>
</li>



<li class="required">
  
  <label for="id_minutos">
  :
  
  </label>
  <select name="minutos" id="id_minutos">
<option value="0" selected="selected">00</option>
<option value="15">15</option>
<option value="30">30</option>
<option value="45">45</option>
</select>
</li>




</ul>
</fieldset>



  <div class="buttons">
    <input class="button" src="button" type="submit" value="Salvar">     
    <a class="button" src="button" href="#">Voltar</a>
  </div>  
</form>
<div id='content'></div>
<script src="http://code.jquery.com/jquery-1.6.4.min.js" type="text/javascript"></script>
<script>
$(function(){
                $.getJSON('http://rast.vitoria.es.gov.br/pontovitoria/utilidades/listaPontos', 
                function(data){
                    var markup = data;
                    $("#content").html(data);
                });
    });
</<script>

wsgi/openshift/templates/registros/sucesso.html
{% extends "base.html" %}
{% block page_title %}Sucesso! - {% endblock %}

{% block content %}
	<div class="row">
		<div class="span8">
			<div class="alert-message block-message success">
				<a href="#" class="close">×</a>
				<p><strong>Sucesso!</strong></p>
				<p>{{ twitter }} às {{ h }}:{% if m == 0 %}00{% else %}{{ m }}{% endif %} horas você será mencionado em um tweet (@twitnerario) com o horário aproximado do seu ônibus.</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="span8">
			<a href="/" class="btn">Voltar</a>
		</div>
	</div>
{% endblock %}